name: Smartvan.io
version: "1.0.0"
slug: smartvanio
description: Manage your smartvan.io devices and custom cards
startup: application
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
boot: auto
hassio_api: true
homeassistant_api: true
host_network: true
full_access: true
map:
  - config:rw
  - "homeassistant:rw"
